# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.runs/synth_1/daphne1_arch.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.cache/wt [current_project]
set_property parent.project_path C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/arbiter.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/arp.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/arp_cache.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/arp_eth_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/arp_eth_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/axis_adapter.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/axis_async_fifo.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/axis_async_fifo_adapter.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/axis_fifo.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/axis_gmii_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/axis_gmii_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/eth_arb_mux.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_axi_core.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/eth_axis_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/eth_axis_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_mac_1g.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_mac_1g_gmii.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_mac_1g_gmii_fifo.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_mac_1g_gmii_fifo_mod.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/gmii_phy_if.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ip.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ip_arb_mux.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ip_complete.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ip_eth_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ip_eth_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/lfsr.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/mac_ctrl_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/mac_ctrl_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/mac_pause_ctrl_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/mac_pause_ctrl_tx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/oddr.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/priority_encoder.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/ssio_sdr_in.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/ssio_sdr_out.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/udp.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/udp_checksum_gen.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/udp_complete.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/udp_ip_rx.v
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/udp_ip_tx.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/AXI_FIFO_Adapter.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/AcquisitionManager.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/AlignFSM.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/Bufgmux_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ClockMUX.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ClockManager.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/DataAcquisition.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/FDRE_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/FIFOManager.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/FIFO_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/Ibufds_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/InputBuffers.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/Iserdese_Block.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/PLL_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/ResetMemory_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/Self-trigger_VHDL.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/Synchronizer.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/bitFSM_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/daphne1_package.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/dsp_slice.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/endpoint.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/eth_module_full.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/frameFSM_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/highPass_FirstOrder.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/rdFSM_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/selfTrigger_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/trigSaveReadFSM.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/Nexys_AFE_Link/wrFSM_Module.vhd
  C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/new/daphne1.vhd
}
read_ip -quiet C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all c:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.gen/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/xilinx/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/xilinx/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/daniel.avila/Documents/GitHub/DAPHNE_V1/DAPHNE_Full/DAPHNE_Full.srcs/utils_1/imports/synth_1/daphne1_arch.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top daphne1_arch -part xc7a200tfbg676-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef daphne1_arch.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file daphne1_arch_utilization_synth.rpt -pb daphne1_arch_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
